name: My Super CI workflow
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: 

jobs:
  hello:
   name: My Hello Job
   runs-on: ubuntu-latest
   steps:
    - name: Print Hello there world
      run: echo "Hello there world!"
    - name: Second steps
      run: echo "Second step hello world!"

  goodbye:
   name: My Goodbye Job
   needs: hello
   runs-on: windows-latest
   steps:
     - run: echo "Goodbye"

  test:
    name: Test the python
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
        platform: [ubuntu-latest, macos-latest]
        include:
          - python-version: "3.13"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.python-version}}
      - name: Install the package
        run: pip install .[test]
      - name: Run the tests
        run: pytest -vv
