name: My Super CI workflow
on:
  push:
jobs:
  hello:
    name: My Hello Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello there world
      - run: echo "Hello there world!"
      - name: Second steps
      - run: echo "Second step hello world!"

  goodbye:
    name: My Goodbye Job
    needs: hello
    runs-on: windows-latest
    steps:
      - run: echo "Goodbye"
